appId: com.alpermar.crossplatform_test
productName: test
directories:
  output: out

mac:
  category: Test
   target:
    - dmg
    - mas

win:
  target:
    - portable
    - squirrel
squirrelWindows:
  remoteReleases: true

linux:
  target:
    - snap
    - deb
    - rpm
    - pacman
  synopsis: A testing app for Electron builds using GitHub Actions
  category: Test